---
#Windows update Playbook
- name: Run Windows updates
  hosts: all

  tasks:
    win_updates:
        category_name:
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpddates
        - UpdateRollups

