---
#Windows update Playbook
- name: Run Windows updates
  hosts: all

  tasks:
    win_updates:
        category_name:
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpddates
        - UpdateRollups
    register:result

    #display restult
    -debug:
        var:result
    
    # to Reboot or not to Reboot how poetic
    -win_reboot:
    when: result.reboot_required
